packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

catalog:
  '@ai-sdk/anthropic': ^4.0.3
  '@ai-sdk/openai': ^4.0.4
  '@iconify-json/lucide': ^1.2.115
  '@iconify/utils': ^3.1.3
  '@nestjs/common': ^11.1.27
  '@nestjs/core': ^11.1.27
  '@nestjs/platform-express': ^11.1.27
  '@types/express': ^5.0.6
  '@types/markdown-it': ^14.1.2
  '@types/node': ^26.0.1
  '@unocss/preset-icons': ^66.7.4
  '@unocss/reset': ^66.7.4
  '@vitejs/plugin-vue': ^6.0.7
  ai: ^7.0.8
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  github-markdown-css: ^5.9.0
  husky: ^9.1.7
  lint-staged: ^17.0.8
  markdown-it: ^14.2.0
  npm-run-all: ^4.1.5
  oxfmt: ^0.57.0
  oxlint: ^1.72.0
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.2
  sass: ^1.101.0
  tsx: ^4.22.4
  typescript: ^6.0.3
  unocss: ^66.7.4
  vite: ^8.1.2
  vitest: ^4.1.9
  vue: ^3.5.39
  vue-tsc: ^3.3.6
  zod: ^4.4.3

minimumReleaseAgeExclude:
  - '@ai-sdk/anthropic@4.0.3'
  - '@ai-sdk/gateway@4.0.6'
  - '@ai-sdk/openai@4.0.4'
  - '@ai-sdk/provider-utils@5.0.2'
  - '@ai-sdk/provider@4.0.1'
  - '@oxfmt/binding-android-arm-eabi@0.57.0'
  - '@oxfmt/binding-android-arm64@0.57.0'
  - '@oxfmt/binding-darwin-arm64@0.57.0'
  - '@oxfmt/binding-darwin-x64@0.57.0'
  - '@oxfmt/binding-freebsd-x64@0.57.0'
  - '@oxfmt/binding-linux-arm-gnueabihf@0.57.0'
  - '@oxfmt/binding-linux-arm-musleabihf@0.57.0'
  - '@oxfmt/binding-linux-arm64-gnu@0.57.0'
  - '@oxfmt/binding-linux-arm64-musl@0.57.0'
  - '@oxfmt/binding-linux-ppc64-gnu@0.57.0'
  - '@oxfmt/binding-linux-riscv64-gnu@0.57.0'
  - '@oxfmt/binding-linux-riscv64-musl@0.57.0'
  - '@oxfmt/binding-linux-s390x-gnu@0.57.0'
  - '@oxfmt/binding-linux-x64-gnu@0.57.0'
  - '@oxfmt/binding-linux-x64-musl@0.57.0'
  - '@oxfmt/binding-openharmony-arm64@0.57.0'
  - '@oxfmt/binding-win32-arm64-msvc@0.57.0'
  - '@oxfmt/binding-win32-ia32-msvc@0.57.0'
  - '@oxfmt/binding-win32-x64-msvc@0.57.0'
  - '@oxlint/binding-android-arm-eabi@1.72.0'
  - '@oxlint/binding-android-arm64@1.72.0'
  - '@oxlint/binding-darwin-arm64@1.72.0'
  - '@oxlint/binding-darwin-x64@1.72.0'
  - '@oxlint/binding-freebsd-x64@1.72.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.72.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.72.0'
  - '@oxlint/binding-linux-arm64-gnu@1.72.0'
  - '@oxlint/binding-linux-arm64-musl@1.72.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.72.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.72.0'
  - '@oxlint/binding-linux-riscv64-musl@1.72.0'
  - '@oxlint/binding-linux-s390x-gnu@1.72.0'
  - '@oxlint/binding-linux-x64-gnu@1.72.0'
  - '@oxlint/binding-linux-x64-musl@1.72.0'
  - '@oxlint/binding-openharmony-arm64@1.72.0'
  - '@oxlint/binding-win32-arm64-msvc@1.72.0'
  - '@oxlint/binding-win32-ia32-msvc@1.72.0'
  - '@oxlint/binding-win32-x64-msvc@1.72.0'
  - '@vue/language-core@3.3.6'
  - ai@7.0.8
  - oxfmt@0.57.0
  - oxlint@1.72.0
  - vite@8.1.2
  - vue-tsc@3.3.6
